import { STAGE } from "../types/reward-types";
import { OPTION_COST } from "../types/reward-types";

export const REWARD_STAGE_LIMITS: {
  [key in keyof typeof OPTION_COST]: {
    [STAGE.CHECK]: boolean;
    [STAGE.MOVE]: boolean;
    [STAGE.ACTION]: boolean;
    [STAGE.DEFENSE]: boolean;
    [STAGE.PASSIVE]: boolean;
  };
} = {
  advantage: {
    [STAGE.CHECK]: true,
    [STAGE.MOVE]: false,
    [STAGE.ACTION]: true,
    [STAGE.DEFENSE]: true,
    [STAGE.PASSIVE]: true,
  },
  disadvantage: {
    [STAGE.CHECK]: true,
    [STAGE.MOVE]: false,
    [STAGE.ACTION]: true,
    [STAGE.DEFENSE]: true,
    [STAGE.PASSIVE]: true,
  },
  aoe: {
    [STAGE.CHECK]: true,
    [STAGE.MOVE]: false,
    [STAGE.ACTION]: true,
    [STAGE.DEFENSE]: true,
    [STAGE.PASSIVE]: true,
  },
  avoidAllies: {
    [STAGE.CHECK]: true,
    [STAGE.MOVE]: false,
    [STAGE.ACTION]: false,
    [STAGE.DEFENSE]: true,
    [STAGE.PASSIVE]: false,
  },
  castTime: {
    [STAGE.CHECK]: true,
    [STAGE.MOVE]: false,
    [STAGE.ACTION]: true,
    [STAGE.DEFENSE]: false,
    [STAGE.PASSIVE]: true,
  },
  consumable: {
    [STAGE.CHECK]: true,
    [STAGE.MOVE]: false,
    [STAGE.ACTION]: true,
    [STAGE.DEFENSE]: true,
    [STAGE.PASSIVE]: false,
  },
  cost: {
    [STAGE.CHECK]: true,
    [STAGE.MOVE]: false,
    [STAGE.ACTION]: true,
    [STAGE.DEFENSE]: true,
    [STAGE.PASSIVE]: false,
  },
  upcast: {
    [STAGE.CHECK]: true,
    [STAGE.MOVE]: false,
    [STAGE.ACTION]: true,
    [STAGE.DEFENSE]: true,
    [STAGE.PASSIVE]: false,
  },
  deals: {
    [STAGE.CHECK]: true,
    [STAGE.MOVE]: false,
    [STAGE.ACTION]: true,
    [STAGE.DEFENSE]: true,
    [STAGE.PASSIVE]: true,
  },
  heals: {
    [STAGE.CHECK]: true,
    [STAGE.MOVE]: false,
    [STAGE.ACTION]: true,
    [STAGE.DEFENSE]: true,
    [STAGE.PASSIVE]: false,
  },
  lingeringDamage: {
    [STAGE.CHECK]: true,
    [STAGE.MOVE]: false,
    [STAGE.ACTION]: true,
    [STAGE.DEFENSE]: true,
    [STAGE.PASSIVE]: false,
  },
  duration: {
    [STAGE.CHECK]: true,
    [STAGE.MOVE]: false,
    [STAGE.ACTION]: true,
    [STAGE.DEFENSE]: true,
    [STAGE.PASSIVE]: false,
  },
  grantsAbilities: {
    [STAGE.CHECK]: true,
    [STAGE.MOVE]: true,
    [STAGE.ACTION]: true,
    [STAGE.DEFENSE]: true,
    [STAGE.PASSIVE]: true,
  },
  immune: {
    [STAGE.CHECK]: true,
    [STAGE.MOVE]: true,
    [STAGE.ACTION]: true,
    [STAGE.DEFENSE]: true,
    [STAGE.PASSIVE]: true,
  },
  imposeVulnerable: {
    [STAGE.CHECK]: true,
    [STAGE.MOVE]: false,
    [STAGE.ACTION]: true,
    [STAGE.DEFENSE]: true,
    [STAGE.PASSIVE]: true,
  },
  resistant: {
    [STAGE.CHECK]: true,
    [STAGE.MOVE]: false,
    [STAGE.ACTION]: true,
    [STAGE.DEFENSE]: true,
    [STAGE.PASSIVE]: true,
  },
  vulnerable: {
    [STAGE.CHECK]: true,
    [STAGE.MOVE]: false,
    [STAGE.ACTION]: true,
    [STAGE.DEFENSE]: true,
    [STAGE.PASSIVE]: true,
  },
  onFailTakeDamage: {
    [STAGE.CHECK]: true,
    [STAGE.MOVE]: false,
    [STAGE.ACTION]: false,
    [STAGE.DEFENSE]: false,
    [STAGE.PASSIVE]: false,
  },
  onAutoSuccess: {
    [STAGE.CHECK]: false,
    [STAGE.MOVE]: true,
    [STAGE.ACTION]: true,
    [STAGE.DEFENSE]: false,
    [STAGE.PASSIVE]: true,
  },
  onSuccess: {
    [STAGE.CHECK]: false,
    [STAGE.MOVE]: true,
    [STAGE.ACTION]: true,
    [STAGE.DEFENSE]: false,
    [STAGE.PASSIVE]: true,
  },
  ranged: {
    [STAGE.CHECK]: true,
    [STAGE.MOVE]: false,
    [STAGE.ACTION]: false,
    [STAGE.DEFENSE]: false,
    [STAGE.PASSIVE]: false,
  },
  reduceDamage: {
    [STAGE.CHECK]: false,
    [STAGE.MOVE]: false,
    [STAGE.ACTION]: false,
    [STAGE.DEFENSE]: true,
    [STAGE.PASSIVE]: false,
  },
  relentless: {
    [STAGE.CHECK]: false,
    [STAGE.MOVE]: false,
    [STAGE.ACTION]: false,
    [STAGE.DEFENSE]: true,
    [STAGE.PASSIVE]: false,
  },
  requiresAmmo: {
    [STAGE.CHECK]: true,
    [STAGE.MOVE]: false,
    [STAGE.ACTION]: false,
    [STAGE.DEFENSE]: false,
    [STAGE.PASSIVE]: false,
  },
  restrained: {
    [STAGE.CHECK]: true,
    [STAGE.MOVE]: false,
    [STAGE.ACTION]: false,
    [STAGE.DEFENSE]: false,
    [STAGE.PASSIVE]: false,
  },
  specific: {
    [STAGE.CHECK]: true,
    [STAGE.MOVE]: true,
    [STAGE.ACTION]: true,
    [STAGE.DEFENSE]: true,
    [STAGE.PASSIVE]: true,
  },
  speed: {
    [STAGE.CHECK]: true,
    [STAGE.MOVE]: true,
    [STAGE.ACTION]: true,
    [STAGE.DEFENSE]: true,
    [STAGE.PASSIVE]: true,
  },
  stunned: {
    [STAGE.CHECK]: true,
    [STAGE.MOVE]: false,
    [STAGE.ACTION]: false,
    [STAGE.DEFENSE]: true,
    [STAGE.PASSIVE]: false,
  },
  summon: {
    [STAGE.CHECK]: true,
    [STAGE.MOVE]: false,
    [STAGE.ACTION]: false,
    [STAGE.DEFENSE]: true,
    [STAGE.PASSIVE]: false,
  },
  teleport: {
    [STAGE.CHECK]: true,
    [STAGE.MOVE]: true,
    [STAGE.ACTION]: true,
    [STAGE.DEFENSE]: true,
    [STAGE.PASSIVE]: false,
  },
  wellspringMax: {
    [STAGE.CHECK]: true,
    [STAGE.MOVE]: false,
    [STAGE.ACTION]: true,
    [STAGE.DEFENSE]: false,
    [STAGE.PASSIVE]: true,
  },
  wellspringRecover: {
    [STAGE.CHECK]: true,
    [STAGE.MOVE]: true,
    [STAGE.ACTION]: true,
    [STAGE.DEFENSE]: true,
    [STAGE.PASSIVE]: false,
  },
  curse: {
    [STAGE.CHECK]: true,
    [STAGE.MOVE]: true,
    [STAGE.ACTION]: true,
    [STAGE.DEFENSE]: true,
    [STAGE.PASSIVE]: true,
  },
} as const;
